### PR TITLE
Udpate seo title

### PR DESCRIPTION
**Pull request by dankmitchell**
### Context
SEO

### Changes proposed in this pull request
- Add `in England` into our SEO title
- Remove SEO title from location page as this is our "homepage"

### Guidance to review
n/a

### CODE REVIEW

**Comment by fofr** [comment]
The problem with this is that, this:
https://find-postgraduate-teacher-training.education.gov.uk/
And this:
https://www.gov.uk/guidance/find-postgraduate-teacher-training-courses-in-england

Now have the same title. The titles should be unique. The front door is the GOV.UK page. Our first page needs to be different.

**Comment by fofr** [comment]
Can we make it:
"Find a postgraduate teacher training course in England - search by location or training provider – GOV.UK"

**Comment by dankmitchell** [comment]
@fofr the problem I saw is when you Google "Postgraduate Teacher Training" both pages show up on the first page so although we say our starting point is on GOV.UK its probably not the reality...

screen shot 2018-11-29 at 11 17 52
screen shot 2018-11-29 at 11 17 49

**Comment by dankmitchell** [comment]
@fofr SEO is important for our service so we definitely need to think about it some more

**Pull request merged**
